### ISSUE TITLE
Caps Lock doesn't work

### ISSUE THREAD

**Issue by jkbelcher** [heronarts/P3LX#4]
When renaming a channel or pattern the caps lock key has no effect.  Tested only on OSX.

**Comment by mcslee** [comment]
Nice find. Very weird, not clear why the keyChar is not reflecting that. Will have to dig into this... since CAPS-LOCK seems to be respected by the normal keyPressed() callback...

**Comment by mcslee** [comment]
Actually, this seems to be a Processing bug.

```
void setup() {
  size(800, 600, P3D);
}

void draw() {
}

void keyPressed() {
  println(key);
}
```

**Comment by mcslee** [comment]
Closing issue, bug filed w/ Processing: https://github.com/processing/processing/issues/5824
