### ISSUE TITLE
Pattern's modulators don't show up in lxstudio pattern modulator UI

### ISSUE THREAD

**Issue by dlopuch** [heronarts/P3LX#5]
If a pattern defines it's own modulators, I would expect them to show up in the lxstudio pattern modulator UI.  They don't, so there's no way of controlling them unless they're global modulators

REPRODUCE:
- Create an LxStudio using IteratorTestPattern
- Open up the modulators ui for the pattern

EXPECTED:
- Since IteratorTestPattern creates a modulator and effectively calls `addModulator()` on it ( https://github.com/heronarts/LX/blob/ca3ded66b6e5865800e61fa3b4ff280d27b08f0e/src/heronarts/lx/pattern/IteratorTestPattern.java#L49 ), I would expect it to appear in the modulators panel
- (actually, only VariableLFO modulators would appear: https://github.com/heronarts/P3LX/blob/c086b7b9ea44f61ff7cae07c317cdd8f4d2ef65e/src/heronarts/p3lx/ui/studio/device/UIDeviceModulators.java#L171 but I'm just using an example with a built-in pattern... problem still happens if VariableLFO's are used)

ACTUAL:
- It doesn't:
![screen shot 2017-07-10 at 1 31 50 pm](https://user-images.githubusercontent.com/1427329/28038821-fd8c4b1c-6574-11e7-8d53-40a3c700db16.png)

CODE DIVE:
For the UI to show modulators, it looks like they need to be in the `LXDeviceComponent#modulation` `LXModulationEngine`: https://github.com/heronarts/P3LX/blob/c086b7b9ea44f61ff7cae07c317cdd8f4d2ef65e/src/heronarts/p3lx/ui/studio/device/UIDeviceModulators.java#L120

When a pattern adds a modulator, it gets added to the `LXModulatorComponent#mutableModulators` https://github.com/heronarts/LX/blob/ca3ded66b6e5865800e61fa3b4ff280d27b08f0e/src/heronarts/lx/LXModulatorComponent.java#L52

(note that an LXPattern extends LXDeviceComponent, which extends LXModulatorComponent, so we're all talking about properties in the same class hierarchy)

It's unclear to me what the relationship between a pattern's `LXModulatorComponent#mutableModulators` and `LXDeviceComponent#modulation` is supposed to be, but I suspect that's why a pattern's default modulators aren't showing up.

Would the solution be as simple as making LXDeviceComponent override `addModulator()` as something like:

```java
// LXDeviceComponent
@Override
public LXModulator addModulator(LXModulator modulator) {
  super.addModulator(modulator);
  this.modulation.addModulator(modulator);
}
```

? 

Or if that's not the intention of LXModulatorEngine, perhaps just have UIDeviceModulator's also call `addModulator()` on `device.mutableModulators` https://github.com/heronarts/P3LX/blob/c086b7b9ea44f61ff7cae07c317cdd8f4d2ef65e/src/heronarts/p3lx/ui/studio/device/UIDeviceModulators.java#L120 ?

**Comment by mcslee** [comment]
This is intentional and by design. There's meant to be a separation here between the concept of user-modulation, which is what shows up in the UI and lives on top of the pattern implementation, vs. modulation which is done in code, and owned by the pattern implementation. There would be various issues with the code-modulators showing up in the UI, such as:
- It's not possible for the user to remove them
- Their arguments are not necessarily parameters, they could be constants, or other modulators, etc.

This is why the modulators that show up in the UI are owned by the separate LXModulationEngine, not by the component itself. Whereas modulators internal to the pattern are directly owned by the pattern component itself.

>> t's unclear to me what the relationship between a pattern's LXModulatorComponent#mutableModulators and LXDeviceComponent#modulation

They are supposed to be separate. LXModulatorComponent#mutableModulators are internal, modified by code, never exposed in UI. And LXDeviceComponent#modulation exists at the UI layer, modified by the user, not by the pattern/effect implementation.

**Comment by dlopuch** [comment]
Fair enough.  It just seems like it would be helpful to see the modulator's UI and control the knobs, even for a pattern-owned modulator.

You can always manually add the modulator's params to the pattern params, but you still don't see the waveform visualizer nor have the ability to tweak the modulation params.  And adding it as a global modulator isn't helpful when it's used just in the pattern.

Seems like there could be a benefit in having the pattern ones display, perhaps with some magic that prevents user from removing them.  As referenced, only the VariableLFO UI would show up since that's the only registered UI (so any specially configured ones won't appear anyways), but I've found it would still be useful to see it.

**Comment by dlopuch** [comment]
(Workaround is for a pattern to simply call `this.modulation.addModulator(someVariableLFO)` instead of `addModulator(someVariableLFO)`, but don't think I would have found that without all the digging in this issue)

**Comment by mcslee** [comment]
> It just seems like it would be helpful to see the modulator's UI and control the knobs, even for a pattern-owned modulator.

I definitely hear you on this, as a tool for pattern development it is very nice to have something like this. I feel like there are 2 different use cases here, one is when developing a pattern... it's nice for everything to just show up in the UI and be tweakable, but then when the pattern is finished, you want to be selective about what controls are exposed to the user.

> You can always manually add the modulator's params to the pattern params to tweak them

Yep, this is the generally recommended practice for exposing internal parameters to the user. But I hear you on the visualizer.

I think for rapid development purposes, the workaround you describe of manually inserting the modulator over onto this.modulation.addModulator() works - and then when you're finished developing you can make it internal again.

Maybe we could also make it easier to expose waveforms in a Pattern Device UI, for cases where it's desirable to have them always exposed to the user.
