### ISSUE TITLE
Disposed `CompoundModulation`s remain in rightpane ui

### ISSUE THREAD

**Issue by l8on** [heronarts/P3LX#7]
Since LEDome is less of a performance piece, my audio strategy is to automatically modulate specific custom subclasses of `CompoundParamater` automatically with specific aspects of the audio input (currently the overall average and the average of bass, mid, treble are working!). I use a channel listener to connect the audio to the current pattern, and dispose of the modulations on the previous pattern. This all works, but when the `CompoundModulation` is disposed, I can still see them in the UI. I worry a bit about leakage when the dome is running all night.

Is there a way to specifically remove a `CompoundModulation` connected to a BandGate from the UI? Or is this a bug?

**Comment by mcslee** [comment]
Do you have code you can point me to? It sounds like you're adding a CompoundModulation in code?

In your project, you could just set up all of the patterns to have the CompoundModulations. You don't really need to remove them from a non-active pattern. If the pattern is not active, they just won't run.

But I think it'll be easier for me to understand what you are asking with some code pointers.

If you're already looking at the audio data directly in code, you might not even need to use CompoundModulation. You could just write your own code that works directly with the audio values.

**Comment by l8on** [comment]
My goal is to make it easy for other contributors to make their patterns react to audio without having to dive too far into the related code. So, yes, I am adding the CompoundModulation in code based on the class of parameter set in the pattern. I currently have 4 subclasses that afford connecting the parameter like `LEDomeAudioParameterLow` that will be modulated by the average of the bass frequencies:
https://github.com/l8on/dome/blob/master/LEDomeAudio.pde#L95-L111

Based on the class name, I create a CompoundModulation with one of the singleton `BandGate`s here:
https://github.com/l8on/dome/blob/master/LEDomeAudio.pde#L268-L288

I appreciate having the ui to tweak things, and I may decide to connect some of the parameters to my midi controller. Given that this will run on a raspberry pi, I'd like to limit resource usage in reasonable ways, so I remove the modulations when the pattern changes here:
https://github.com/l8on/dome/blob/master/LEDomeAudio.pde#L313-L321

The fact that they remain in the UI has me concerned about memory usage over time as the animations cycle overnight.

(Side note: I've also noticed that even though I'm setting the `minFreq` param of one of the `BandGates` to 256, it ends up being set back to 120 at run time).

**Comment by mcslee** [comment]
Got it. When you want to clean the modulation up, you shouldn't dispose of it directly.

Rather, do the opposite of:
      this.lx.engine.modulation.addModulation(compoundModulation);

Which is:
      this.lx.engine.modulation.removeModulation(compoundModulation);

https://github.com/heronarts/LX/blob/master/src/heronarts/lx/LXModulationEngine.java#L115

I believe if you use that call, everything will be taken care of fine, the UI will be torn down and the component disposed of.

> (Side note: I've also noticed that even though I'm setting the minFreq param of one of the BandGates to 256, it ends up being set back to 120 at run time).

Do you know when it's reset to 120? You might try adding an LXParameterListener to the parameter and then just print a stack trace in the onParameterChanged() method to find out where that's happening.

e.g.
```
minFreq.addListener(new LXParameterListener() {
  public void onParameterChanged(LXParameter p) {
    // log to the console, see a stack trace of what code changed this parameter's value...
    new Exception().printStackTrace();
  }
});
```

Let me know if that reveals anything.

**Comment by l8on** [comment]
@mcslee Thanks for the tips!
a) Using `lx.engine.modulation.removeModulation` works like a charm.

b) Following the stack trace, it seems that because I'm setting `minFreq` to a value that is higher than the default `maxFreq` I'm running into this code in `BandGate`:
https://github.com/heronarts/LX/blob/master/src/heronarts/lx/audio/BandGate.java#L205-L206
I understand why the code is there, and I can fix it by setting the maxFreq first.
However, it may be prudent to instead change the `maxFreq` to match the value set to `minFreq` such that the intent of the change is kept while still keeping things consistent.

**Comment by mcslee** [comment]
Ah yeah, that'll do it. I'm going to leave it as is for the time being since I think some of the UI components rely upon that logic for bounds-checking. Setting max before min will definitely work.
