### ISSUE TITLE
String compare bug in UIToggleSet

### ISSUE THREAD

**Issue by phil-levis** [heronarts/P3LX#8]
When you call `setValue` on a `UIToggleSet`, passing a `String`, the method checks for equality using `==` rather than `String.equals`. This means that you have to pass the identical `String` object, and not, say, the same string read in from a file for configuration. It should test for equality with `String.equals`.

```  public UIToggleSet setValue(String value) {
    for (int i = 0; i < this.options.length; ++i) {
      if (this.options[i] == value) { // Bug
        return setValue(i);
      }
    }
```

Here is an example test case. Just run `java StringBug Test` to pass `"Test"` at the command line.

```
import heronarts.p3lx.ui.component.UIToggleSet;
import heronarts.lx.*;

public class StringBug {
    public static final String paramStrings[] = {"Test"};
    public static void main(String[] args) {
        UIToggleSet toggle = new UIToggleSet();
        toggle.setOptions(paramStrings);
        String testString = args[0];
        toggle.setValue(testString);
    }
}
```

**Comment by mcslee** [comment]
Whoops, sorry about that.

Fixed:
https://github.com/heronarts/P3LX/commit/434924045de612423b3e9581bb0e5b04e31fe902

**Comment by phil-levis** [comment]
No problem! Can you push the fix to -IDE?

**Comment by mcslee** [comment]
Yep - latest builds are pushed here:
https://github.com/heronarts/LXStudio-IDE/commit/771c87ef26dc1f9a36f4d760a5375850f77f0659

Just FYI, quite a few other bugfixes/enhancements in there as well. Let me know if it causes any other issues.
